"""Validate decks/<archetype>/deck.csv against the engine and emit
ptcg/decklists.py with the decks that pass both gates.

Run once (base interpreter): python scripts/build_decks.py
One engine battle per process — do not run alongside pytest/other engine users.
"""
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if REPO not in sys.path:
    sys.path.insert(0, REPO)

from ptcg.decks import is_legal, is_playable
from ptcg.engine import load_sample_deck

DECKS_DIR = os.path.join(REPO, "decks")
OUT_PATH = os.path.join(REPO, "ptcg", "decklists.py")


def read_deck_csv(path):
    with open(path, encoding="utf-8") as f:
        lines = [ln.strip() for ln in f.read().split("\n") if ln.strip()]
    ids = [int(ln) for ln in lines[:60]]
    assert len(ids) == 60, f"{path}: expected 60 ids, got {len(ids)}"
    return ids


def main():
    archetypes = sorted(
        name for name in os.listdir(DECKS_DIR)
        if os.path.isfile(os.path.join(DECKS_DIR, name, "deck.csv"))
    )

    decks = {}
    skipped = {}
    rows = []
    for name in archetypes:
        path = os.path.join(DECKS_DIR, name, "deck.csv")
        ids = read_deck_csv(path)
        legal, legal_why = is_legal(ids)
        playable, playable_why = (False, "skipped (illegal)")
        if legal:
            playable, playable_why = is_playable(ids, n_games=8, seed=0)
        reason = "" if (legal and playable) else (legal_why or playable_why)
        rows.append((name, len(ids), legal, playable, reason))
        if legal and playable:
            decks[name] = ids
        else:
            skipped[name] = reason

    print(f"{'name':<28}{'ids/60':>8}  {'legal?':<7}{'playable?':<10}reason")
    for name, n, legal, playable, reason in rows:
        print(f"{name:<28}{n:>8}  {str(legal):<7}{str(playable):<10}{reason}")

    sample_ids = load_sample_deck()

    if len(decks) < 6:
        print(f"FAILED: only {len(decks)}/{len(archetypes)} archetypes passed both gates "
              f"(need >= 6); not writing {OUT_PATH}")
        sys.exit(1)

    lines = [
        '"""Curated Mega-era Standard decklists as card-ID lists.',
        "Generated by scripts/build_decks.py from decks/*/deck.csv — do not hand-edit.",
        'Each deck was engine-validated: is_legal AND is_playable(n_games=8)."""',
        f"SAMPLE_IDS = {sample_ids!r}",
        "DECKS = {",
    ]
    for name in sorted(decks):
        lines.append(f"    {name!r}: {decks[name]!r},")
    lines.append("}")
    lines.append("SKIPPED = {")
    for name in sorted(skipped):
        lines.append(f"    {name!r}: {skipped[name]!r},")
    lines.append("}")
    lines.append("")

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"wrote {len(decks)} decks (+ sample), skipped {len(skipped)}")


if __name__ == "__main__":
    main()
